package server

// String representing html for simple service access
const formHTML=`
<html>                                                                                                   
<head>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>                                      
<script type="text/javascript" src="//www.google.com/jsapi"></script>

<script>
var status_location = "";
</script>
</head>

<table>
<tr>
<td><H2>Evaluate EM Segmentation</H2></td>
<td><a href="http://janelia.org"><img src="https://raw.github.com/janelia-flyem/janelia-flyem.github.com/master/images/gray_janelia_logo.png"/></a>
</tr>
</table>

<a href="http://www.janelia.org/fly-em-recon">Fly EM Reconstruction Team</a>
<br>

<span id="instructionsheader" style="cursor:pointer;color:blue">instructions+</span>
<div id="instructions" style="display:none" width="50%">
<p>
This web service will compare a label volume with our ground truth.
The first input is a gzipped h5 file, where the labels are stored
in the dataset named "stack" with coordinates z,y,x.  The second input gives
a list of edges between the labels and their edge certainty weights 
<a href="/static/graph.schema.json">(specification)</a>.  Examples of both
are given below.  The labels should be generated by segmenting the EM
grayscale data <a href="/static/grayscale.tgz">(download image stack)</a>. 
</p>

<p>
Similarity between ground truth and segmentation is done using Variation of Information (VI).
We use a synapse and volume-based VI comparison as defined <a href="http://arxiv.org/abs/1409.1199">
here</a>.  We apply automatic focused proofreading using the provided uncertainties.
We use the strategies defined <a href="http://arxiv.org/abs/1409.1199">here</a>.  We report the number of decisions that need to be made and the resulting VI.  Ideally, good uncertainties would lead to a small number of decisions that greatly improving the VI.
</p>


<b>Examples Files:</b><ul>
<li><a href="/static/labels.h5.gz">Sample zipped h5 file</a></li>
<li><a href="/static/graph.json">Sample graph file</a></li>
</ul>
</div>

<hr>

<br>
<table border=1>
Submit Segmentation Job<br>
<form id="calclabels" method="post">
zipped h5 file <input type="file" name="h5file" id="h5file" accept=".gz"><br>
graph json file <input type="file" name="graphfile" id="graphfile" accept=".json"><br>
<input type="submit" id="submitbut" value="Submit"/><br>
</form>
</table>

<hr>
<hr>

<br>
<div id="status"></div><br>
<div id="results"></div><br>
</div>

<script>
    setInterval(loadUpdate, 1000);
    $("#metricsheader").click(function() {
        $("#metrics").slideToggle();
        if ($("#metricsheader").text() == "+") {
            $("#metricsheader").html("&#8722")
        } else {
            $("#metricsheader").html("+")
        }
    });

    $("#instructionsheader").click(function() {
        $("#instructions").slideToggle();
        if ($("#instructionsheader").text() == "instructions+") {
            $("#instructionsheader").html("instructions&#8722")
        } else {
            $("#instructionsheader").html("instructions+")
        }
    });

    $("#calclabels").submit(function(event) {                                                           
      event.preventDefault();

      var formData = new FormData();
      
      // load h5
      var x = document.getElementById("h5file");
      if (x.files[0] === undefined) {
            alert("Must provide h5 file");
            return;
      }    
      if (x.files[0].size > 2000000) {
            alert("H5 file is too big");
            return;
      }
      formData.append("h5file", x.files[0]);
      
      // load graph
      var y = document.getElementById("graphfile");
      if (y.files[0] === undefined) {
            alert("Must provide graph file");
            return;
      }    
      if (y.files[0].size > 4000000) {
            alert("Graph file is too big");
            return;
      }
      formData.append("graphfile", y.files[0]);
      
      $('#status').html("Uploading...");
      $('#results').html("");

       $.ajax({
        type: "POST",
        url: "/formhandler/",
        data: formData,
        contentType: false,
        processData: false,
         success: function(data){
            status_location = data["status-callback"];
            $('#status').html("Processing...");
            document.getElementById("submitbut").disabled = true;
        },
        error: function(msg) {
                $('#status').html("Error Processing Results: " + msg.responseText);
          }
        });
    });
    function loadUpdate() {
        if (status_location != "") {
            $.ajax({
                type: "GET",
                url: status_location,
                success: function(data){
                    status = data["status"];
                    $('#status').html("Status: <b>" + status + "</b>");
                                   
                    // grab html string
                    results = data["html-data"];
                    $('#results').html(results);
                
                    if (status == "Finished") {
                        status_location = "";
                        document.getElementById("submitbut").disabled = false;
                    }
                    if (status == "Error") {
                        status_location = "";
                        document.getElementById("submitbut").disabled = false;
                    }
                },
                error: function(msg) {
                    $('#results').html("Error accessing server");
                }
            });
        }      
    }                                                                                                
</script>                                                                                                
</html>                                  
`
